version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - .:/plugin
  lint:
      image: buildkite/plugin-linter
      command: ['--id', 'robertkruk/spell-checker']
      volumes:
        - ".:/plugin:ro"